version : 2.1
 
workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main

jobs: 
  build:
    working_directory: ~/ExampleApplication
    docker:
      - image: cimg/node:19.7.0
    steps:
     - checkout
     - run:
      name: update-npm
      command: 'sudo npm install -g npm@5'
     - resore cache:
      key: dependency-cache-{{ checksum "package-lock.json"}}
    - run: 
        name: install-npm
        command: install-npm
    - save_cache: dependency-cache-{{ checksum "package-lock.json"}}
      paths:
        -.node_modules
